# Generated by Django 5.0.3 on 2024-03-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pi", "0002_aula_estudante_aulas_professor_aulas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aula",
            name="aluno",
        ),
        migrations.AddField(
            model_name="aula",
            name="alunos",
            field=models.ManyToManyField(
                related_name="aulas_estudante", to="pi.estudante"
            ),
        ),
    ]
