# Generated by Django 5.0.3 on 2024-03-08 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pi", "0003_remove_aula_aluno_aula_alunos"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="sala",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="pi.sala"
            ),
        ),
    ]
