# Generated by Django 5.0.3 on 2024-03-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pi", "0005_presenca_prova_nota"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="numero_lista",
            field=models.IntegerField(default=1),
        ),
    ]
