# Generated by Django 5.0.3 on 2024-03-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pi", "0006_aula_numero_lista"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudante",
            name="reprovado",
            field=models.BooleanField(default=False),
        ),
    ]
